Checking movies at https://www.pelismkvhd.com/
New movie uploaded!
THE CURSED (2021) BRRIP 1080P HD MKV ESPAÑOL LATINO
https://www.pelismkvhd.com/2023/04/the-cursed-2021-brrip-1080p-hd-mkv-espanol-latino/
{'data': {'edit_history_tweet_ids': ['1642919902649413634'], 'id': '1642919902649413634', 'text': 'New movie uploaded!\nTHE CURSED (2021) BRRIP 1080P HD MKV ESPAÑOL LATINO\nhttps://t.co/Nsk0w7Innm'}}

13:00:01.707422: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:05:03.722848: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:10:05.189316: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:15:06.677539: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:20:08.141432: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:25:09.665948: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:30:11.197341: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:35:12.560786: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:40:14.141291: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:45:15.697436: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:50:17.269274: Sleeping...

Checking movies at https://www.pelismkvhd.com/

13:55:18.637301: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:00:19.781299: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:05:21.225334: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:10:22.493596: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:15:24.093764: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:20:25.868771: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:25:27.347884: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:30:28.674922: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:35:30.173294: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:40:31.669422: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:45:33.105453: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:50:34.671772: Sleeping...

Checking movies at https://www.pelismkvhd.com/

14:55:36.257310: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:00:37.957532: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:05:39.499790: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:10:40.805731: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:15:42.358009: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:20:43.831535: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:25:45.126307: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:30:46.706853: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:35:48.131903: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:40:49.579406: Sleeping...

Checking movies at https://www.pelismkvhd.com/
New movie uploaded!
AGENTE FORTUNE: EL GRAN ENGAÑO (2023) BRRIP 1080P HD MKV INGLÉS SUBTITULADO
https://www.pelismkvhd.com/2023/04/agente-fortune-el-gran-engano-2023-brrip-1080p-hd-mkv-ingles-subtitulado/
{'data': {'edit_history_tweet_ids': ['1642961633998675968'], 'id': '1642961633998675968', 'text': 'New movie uploaded!\nAGENTE FORTUNE: EL GRAN ENGAÑO (2023) BRRIP 1080P HD MKV INGLÉS SUBTITULADO\nhttps://t.co/obRvwubEWA'}}

15:45:51.141336: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:50:54.006131: Sleeping...

Checking movies at https://www.pelismkvhd.com/

15:55:55.549337: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:00:57.205338: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:05:58.755104: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:11:00.293118: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:16:01.701201: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:21:02.773411: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:26:04.106577: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:31:05.477350: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:36:07.075247: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:41:08.316032: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:46:09.857479: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:51:11.429441: Sleeping...

Checking movies at https://www.pelismkvhd.com/

16:56:12.998125: Sleeping...

Checking movies at https://www.pelismkvhd.com/

17:01:14.407231: Sleeping...

Checking movies at https://www.pelismkvhd.com/

17:06:15.765165: Sleeping...

Checking movies at https://www.pelismkvhd.com/

17:11:17.099056: Sleeping...

Checking movies at https://www.pelismkvhd.com/

08:32:04.410117: Sleeping...

Checking movies at https://www.pelismkvhd.com/

08:37:05.898229: Sleeping...

Checking movies at https://www.pelismkvhd.com/

08:42:07.587499: Sleeping...

Checking movies at https://www.pelismkvhd.com/

08:47:09.086233: Sleeping...

Checking movies at https://www.pelismkvhd.com/

08:52:10.487473: Sleeping...

Checking movies at https://www.pelismkvhd.com/

08:57:11.863519: Sleeping...

Checking movies at https://www.pelismkvhd.com/

09:02:13.486330: Sleeping...

Checking movies at https://www.pelismkvhd.com/

09:07:15.849090: Sleeping...

Checking movies at https://www.pelismkvhd.com/

09:12:17.287517: Sleeping...

Checking movies at https://www.pelismkvhd.com/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1043, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff7bb49d7e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pelismkvhd.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7bb49d7e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/d_irra/git/pelismegamegabot/src/twibot.py", line 78, in <module>
    main()
  File "/home/d_irra/git/pelismegamegabot/src/twibot.py", line 55, in main
    peliculas = get_peliculas(url)
  File "/home/d_irra/git/pelismegamegabot/src/twibot.py", line 27, in get_peliculas
    response = requests.get(url)    
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pelismkvhd.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7bb49d7e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
